<?php

$useragent = "xxxx";

$cookie = "xxxx";

//SCRIPT GRATIS, JANGAN RESHARE DITAMBAH PASSWORD! ALLAH MELIHAT APA YANG KAMU KERJAKAN

//THIS SCRIPT IS FREE, DONT RESHARE IT WITHIN ADDING PASSWORD INSIDE!

//GOD ALWAYS SEE WHAT YOU DO