<?php

// ISI SEMUA DATA DI BAWAH INI
// PERHATIKAN BAGAIMANA ADMIN MENGISI DATANYA
// JANGAN LUPA SUPPORT CHANNEL ADMIN

$link = "https://manicoins.com/home?BTC=0&BCH=0&BCN=1&DASH=1&DGB=1&DOGE=1&ETH=0&LSK=1&LTC=1&XMR=0&NEO=1&PPC=1&POT=0&XXP=0&STRAT=0&TRX=1&WAVES=1&ZEC=0&ADA=1&ETC=1&EXG=0&EXS=1&PIVX=1&RDD=0&XTZ=1&VTC=1&KMD=1";
$user = "xxxx";
$cookie = "xxxx";