<?php

// ISI SEMUA DATA DI BAWAH INI
// PERHATIKAN BAGAIMANA ADMIN MENGISI DATANYA
// JANGAN LUPA SUPPORT CHANNEL ADMIN

$user = "xxxx";
$cookie = "xxxx";

// ISI 1 JIKA MAU KLAIM
// ISI 0 JIKA TIDAK

$BCN = "1";
$DOGE = "1";
