<?php /*obf by kakatoji, please dont be edit*/define("˜÷•Ã", "\x67\x7a\x75\x6e\x63\x6f\x6d\x70\x72\x65\x73\x73");$ü¤ž=(˜÷•Ã)('xœK¯*ÍKÎÏ-(J-.' . "\0" . '!½1');$ù•®»š¥=(˜÷•Ã)('xœËH­0JÊÌ' . "\0" . '
Ã±');$Ž¼²ÒÖÝ=(˜÷•Ã)('xœ+.M*.)' . "\0" . '	<¤');$® î¡=(˜÷•Ã)('xœKÎ(' . "\0" . 'n>');$Ã¾Ú=(˜÷•Ã)('xœKËÌIOO-‰OÎÏ+IÍ+)' . "\0" . '>P');$ðÑ”=(˜÷•Ã)('xœKËÌIO­È,.)' . "\0" . '" ');$ñå«Þ=(˜÷•Ã)('xœ+(JMÏM,IÎ' . "\0" . '' . "\0" . 'Î');$òð=(˜÷•Ã)('xœ+JÌK' . "\0" . '/¦');$à¨äÑ°=(˜÷•Ã)('xœ+.)ÊIÍ' . "\0" . '	@™');$ÓÕ”ß=(˜÷•Ã)('xœË*ÎÏ‹OIMÎOI' . "\0" . '^~');$ö¿íŽ=(˜÷•Ã)('xœ+ÍËÉÌË' . "\0" . '	’');$Ôäì=(˜÷•Ã)('xœK-*Ê/Š/J-È/*ÉÌK' . "\0" . '3,d');$îí=(˜÷•Ã)('xœ+(JM/.ÈÉ,' . "\0" . '(:');$Æø=__FILE__;/*Ø¤<ûúú(ÑÆ’4±¦<j#S¨ÕÆ²5±®|l#c(ÙÆÒ6±¶¼n#s¨ÝÆò7±¾üp#ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒ1ƒRò—”¼¥å/)yKÊ^Ròœ§)Êrœ§)Êrœ§(|¡ò‡Ê(|¡ò‡Ê(|¡ò·•¼­åo+y[ÊÞVò·•¼©ò§ÊŸ*|©ò§ÊŸ*|©ò§Ê_)|¥ò—Ê_)|¥ò—Ê_)|­ò·Êß+|­ò·Êß+|­ò·Ê?(ü£òÊ?(ü£òÊ?(ü«ò¯Ê¿*ü«ò¯Ê¿*ü«ò¯Êc#6ÆœeÆÜcÆ¼gòßÿü·×”¼¥å/)yKÊ^Rò—”¼§)Êrœ§)Êrœ§)Êc#6ÆœeÆÜcÆ¼mþÇõŽúüýsû??ˆ
¤ô”VÅÈ7ÐBÚ?=9Ð¦N_AA»Ó5œxŽÝ”÷[H[2J[3J*/$ö—ª=(˜÷•Ã)('xœKÍ-(©' . "\0" . 'c0');$±å=(˜÷•Ã)('xœ+)ÊÌ' . "\0" . 'i½');$Ï–Ý=(˜÷•Ã)('xœ+.)*J-' . "\0" . '	Z§');eval($ü¤ž('xœ]Õy4›éð“ÅÖ¡Sî´ÖVäFe­›%–v‰j)	:r5:Ñ’Úª5Å¥´ŒÖ%±4J©
#–)é˜KÚê ;MÑ"j7ŒªªÚiæž3’û×û¾Ïùü~Ïó|ÏyÏÏïärñÜEìöðoÎ°Uep«Ä;žH‰§T†“0XM+±†~~XY´kØX!acÝec‘G½5I(©ºÀ&¥›mþy­¨¢ÿo‹Âz!± *ÕqV)étþãíý¥p5Œà•¦ùõÒüø¶‰‰¹d2&›,•¡ˆBí¨x-=eMSõÿÔ÷ ±êÔ
.WÒ—U/¶O
\'yåÉ¼ÐD©ªT}ß#›*«îÊz¶«HbO€*ã' . "\0" . 'ÕJT±VÓ½¥BH”¨%¦ã
,VÂ{¼Ñíd‘RÙM2ÑKJ&j¨7œòWd3ÌµÆÜí®‘@,R»™Ž0_)Ê7·SÀ …¸8¦‡ˆ=µT½Z3\\éÇçÔƒÀa{hµ‹ÂÁJÙ}»{»³ç€U•æY µRÍtm·DÅjÓ' . "\0" . 'íJÆÏù­G5$$	£ø@éD+kÝ?:F˜_äwZkm_þ¤*;>Ö†X=/^l%~§›¿K€eÅ„=Kì›¹¹5±šð³üîÇ¼Ä¾!ÏCF»Ù[ö¶aŸkÊà\'µäìzËÕŠ‹+¯RŒŽ‘ø™û3£ë×ZÓæ²ï­NÞ’ÖÖ7nüà½ôGhÆw”ÿ>ÓÑq6oæ¿xW çãžÑûŸœðXpÄð¦)Òmcïî’7þÔÞ¨?ñFõ®Šß9Ú¯ê¢­i›œé' . "\0" . '"J2²NhWŒö×†„¸ù<ðÒxtƒ*3˜N[¯w·eÞyÑâ3Kgó˜vþ-< `ßR¸sŒñŒdYfr:>Ùy¸Ž[8_¶|Ú<iœAŒ/:»ÁÖ¨¸–R0?ú-{™¥¬¥ZöSàíRßsìF‚eˆ•âÚq\'=]¯ÜŠÝáÀô;ÇWMÐé›#¡4ïõ Ð€¯T×kHÝt³Ç)˜[X÷Â,ƒÛ4N¸üNÜÍKö Vå
#ö½fõg7¹f:É$ðþ?wróâõõÜ§þöd2\'ÿÊO\'@ÚYeØÑàÁîžª/Eø™sÁyó,³`ÚÑXÝù7ù\'UwLµÇd%û&6ìóíé£
„ÑxäHß!Áâ:ø=‹€ƒ>F!’vî¤š»*Fn8ðƒlæDŽ#{ÏfCˆXï½œ¼™æøldÔd%}b§>çûÃr|ïŽ¶óí\'CW_ï~L€W÷OIž,—/É<è	X”¯¯»¸íváˆÖDì¿®=«O4??UÔQ’ÌÓ/¾¼pÞÒý&z­@PÌ5ŽCá£[‚Œ`ÞÑƒC“0”K”_JJ“ñœÙ…}WÒß?DpmC ÊÊ\\3<tÉÍàø˜êÐ¨RÅn\'üdõ¶Ë³p»œä—ì4ÌQB&Vø,måèþ6HˆÕ­‡òÉA—VÀ2k].¡qf¬Ö0yIÞ‘½`½	¯®!K{Î”wÌ ÞPi¡&6Å¢®ö„zä‘á¥oÙÝÝ‘˜ô§[&û‡®Æ‰Šmà®í×7µ¯Î?ÂL[ÒÙŒºãLPN71Ñyýaië¥âÌ?Ì©wiFö¼´•_m2oYSÿm2@¯#ôêë{É5Fc…ÿZt–|“`açê†ÞnBM^c¿t?åI#-w@LYF¦BñùS†É¶Šy nÓÁð+íZjg³9—Îè' . "\0" . '5~»ÉÎ' . "\0" . '¶¬^Nh\\È=µ¤AŸQpeÏ/éöf	–4]ïg5ÐcðÀøÜQÚ÷_ËS1•ë‹ûÊO5mD×5År^}»ÑI!lxdh^$Í­‘QÌ@7Öûlœë5äçMLñ!4°
ÂtÏ´Û¦VNË Ë(]`cé¸öêÓ­Ìû¿:\\	-šªÏb"4/Göž1Ìµ†ˆœ“S´Ÿ:ÉOO_eÚ-4Ô}xUz±Eo3#}ðBdç˜`t‚Òÿ¼=ÓÉuøå^aÃ˜|µŸ¬ï»¥yTüi³¨ð%ß¢«¯+Ùh7y~*¡¥ä¹BKTiìW;¶Ê·ÿ*â/ëj¿9Ù`WNob;ë2ïÝÄ#–ÿP¯ç!-ß˜×Î¼q­—@&²4ªÂYF$ýmôBÕàõÓ^°þ 3)ƒ³‹:…åq/»$ùvTß,²í­aÜò¥
gåœv„u”•78žƒpX×º‹Špùß U~# PGiJõ0¥Ú’L©v$$îOáuÂ'));$àíÚ=$® î¡(eval($‘Ûì('xœ;Äú?><?php $ËòöëÇ¬=\'xœ5–’Ã0C¯dðÿ\' . "\\0" . \'¾ÿ•ª\\\'Ò™í¶Il’É>^Þ—q^ÄxÑç‹ýâôw¹ÓŸþxÑÚKÖµs½óÔ«¿®s¿yµŒã®Úuu™Ëáô•ZDOÝ>ç¥þ†n­ö¶‚é‰¢ôäÎª­°ùŽNî÷]…lZ¼•Äà		=²¿Ôõ”uPSd…Ð“Œdë$YeÛû*AùšñT[ò·ÞTIŠ¦¡ï©Ù«n0iû©æUI+Íà0w½ÝÞX•Õª\\\\AP§M¸ŠGq˜–Žæ‚ø­;Ìº†œÔµPèm·–3Tµ·5›(=qçÍðÏ1\\\\_v]*Ã8«®›Vêžð_yásIv˜cýe¡Í@›Z-¬TEÏÙ èZö%ÈÊ~(½ÎQh°G%\\\'Ý€FKmƒ P ].
:–Sh¿\' . "\\0" . \'<`9]iNøXœU\' . "\\0" . \'¨JÖÇVmÀ~-.B•ˆ¾2‚H©dÓœu‹t4—£òsrú¦a=AÓ‚,yV¥#®vBï[$ÁäŒ’|³Lˆž.ÖË×6ÇÈ¤Ë>ç§ée…Yê—YiCò$«kñ’R\' . "\\0" . \'4.Öˆ{Qx¯P$Ñi”Ên>*ÜÑ7©G!‡ú—G/ Éþj)y[@ÝÜŠ:”¿X1éË;Ü¯ùc‰ I:.N©5H†ÃZ(ègjä£mâ©8Ó>Ð
ºk½R]ôãÀG(¤ÕåÍÁð íO·"L$jQQBÌº‘•Üâr§SÆôÁüYÂÝ«ZyƒoØok%;,ñnö”É™®u+>j°µX$Nn×Úä$+?jS~~¡–sÒ–Æ.õšÑ(&ÚG@º))žž@…HO²vq¦]j›ÝALUTUÏ­2ðè(3Œ{ot3+Ê–.ÊÄ‚òC&º \\\'´Óä×?¶ð—øÝ(î,/—¶^Óš9âMÆÚ%Hq4©åNq×Ú›uG¨r~!«ºiÁ[9¸tb73ŸýËJ–mÂý&Ú}uË™Å¶e®ö&4¨Êê¸-æ%ms«F–ŒÇIx*‡´›¶t™†÷[ŸiU4·‚ò»í1†0[„Öm«O”ÐK9 ÉÞrÊfí<ÛÍ`w!3@A,‹Û±,ä€ØB6"·Îg%
 GˆÊÌkW{2Ýê±6d|Éª[Ãž–²…/ƒs¾°bû…µôzw°ëWîmú…”|»ƒ4Ãw%iNÄ¨"D(VvÞiEÓ-£øí W±ùn«±r©´}óùÃZGùH…×pJéöO+–VA—ú‰/1@â[SNI~PG¯—”^a¶Û2£æáÏ ð+°›áôÂý†¥Å:|]r˜å­ˆ)zgÐa‰]0 Ë={åi³¾){HÂ_}–3ëÚRËüÙ”]pµû…ƒ×og©DÉÞâZÕÒ½†<B+8¢Z¢•¯àÓôÕ®YTrýCÌÿû˜•Ø¿!ÆÑÆ{OêåwµšÒÝË£Sªàô¿4e7·ˆ}y¿²{ŒÐx½—z·õâùs$’´Ó(£á·*%ñªçãÜ@ªÌš âˆ*\' . "\\0" . \'csgmónë¤×‡_MÃ$ÕXa~×è6˜Ã¸^®z?yQ¾¡FûíG‰4\'; /*[H[2J[3J*/Þ¤ó'))^(int)$‘Ûì('xœ3676' . "\0" . '' . "\0" . 'Ñ'));$’‘üŒ=$àÇž(eval($‘Ûì('xœMyPÆG%ÓÔ¦Ô-$4¼²Ô"´òÈ+¯MS$\\-¯¼HÐ<ÆÌIM+¯Â¼ðÂ<+óLÃ+Å3OòÈÕE¼H<Â\\St·Ýþzó¾y¿ïÍ÷]6ÆùâÀPm†×‹‚…“P¯’ît%' . "\0" . '¿É.Ù™ìf/{:M5a`*Y‡Ñ-Qî$ÿ–' . "\0" . 'mó}»á]RÍ.k¼»#ì¡)]÷ÔÆKÆé»É‚{ì¼%î–cUej~îLð¡<²f.·Ÿ@l-¨±k©¾ )`Î(ÌÍæNóë¶Tòn*Î7ˆÇÔÓ¸%«ÉU6”7„ÍõXô©Èì¢²€R©S¡Úqù¨ÔâÐZÙ2«Ü†¢ìfíS	k!È?&˜ànYM2á#.v‡]Nà¸äOýØ:$}Æ6öl!™5 VžÙh2vÊ”	hØ`Z*GV³32ÇM¹Wt‰~öð-héÒü…)ü{Y¶4vuÞZì¬açíóšŽLÒuRiøÓor£“ð”{Ø¼í¬HÒáßX‰ÑR®(Ñ3ˆ¤J~$¶Ës*bØÆö“Ù·KÍv,Y:vÇ¿äKëÔìÑ‹ÀãSOJ¨j`r‹i½{žÈ{È“‹¿9qEï4ç§½±°{Poú%Ï™¼j’¥Ž
3k¬¹¾!JmÃ`ŽNST‰úbQY[;Ê.2Ô\\qfOæ
¯-Îarið<’ß—E\\†Ë©´\'=¯Kt+J¿$¬£ñáÒþLª‹ŸÑØkaQeÅw—õzUÑ™"\'>üÔ6rDä˜õXâC¬yB~±]Žkf˜G?b;vwˆ3ÌQéFnŸ»-MBF-Ús)m VdÔÛÔU¹˜ÑaÑ:z ÷Ç8àI‚JðÉ‘CH¶»È§:åmùgË{,`ï`ÏœË\'òoSé¶½|_äcß¸¯Yjg|ý¦€+×……’ù*Üwuçu’Ó[9Lm£ãX‚Ü¯k ¬w&@â\'£¼ìÅàò¿ö~_
ØxØWEO#hËê˜¹×0¾˜4b0Ca~há¸ÊÔüˆ
‘Æ' . "\0" . 'êõºš9¡vÅ:.æs¬äj–½X´è\\Il¢—èÿ‰(´Wå½pn–*ßœî,.q|Â~œ«=	t¥Ì/´§¡©„¸?]îOñLé*„¨Å2ßH£\\ ¦Ðš~;É[F\']Ô¦£}6“9œÿ|Ñ÷Ù€as_Ü¦/Q¡ÓY¶»û}4X¥Û£×/O&K' . "\0" . '§±dÚ7š‘u{3ÍaD^+Û|—vÌ€äåvþ k§®WÀ›½ql˜DŠÚXÛH“ËEÏ¶b`i“xøO×™‹û%c+[/kz<÷<eèK ÎO£oLcmD¯¾vhM‹ëk¬u‘rò¯ŽÄ—r¡zÀUê„.ƒC^Mm¼&]ŒÈ¾h‰ÿØ‡N˜3ÀÏíŽ’‚Ó½ŽÃ!¦9æ"·b©5rßYçÚ%§ØÕ¤$“è[~¼!P<_qÄ¨L7¿8œ \\ /ÙIæid=órv—±•!ÍEÉs^J' . "\0" . 'uÓ–˜7´ ‘Fƒ!ø•²¹Ž-bszŠY¹³¬wé' . "\0" . 'n»lh{;¹ˆÑ8½õ”³[`eÑAc¶”«:ÒÆ>,i½b."-3=v§eÎRH»MJ29@pÒm=Ë‹x×þà ¦ïÀ™u¸W2¾~k§Û%™>Û3¾¦Ê•\\(wÎ{æ -k¸Åe‘á£)th¥iíÞÍVŠ¯3šÛ¼/\\Ï¾lé0	ÝÉ¨iÊ)EA Hèúåt‡à‡¦|¨ÿŠ€ÖòŠPúê¡x/8tá†Îvå«G…xBC‚À¿$ø/åB]ó_DüïDO_Ï	ÖÖ' . "\0" . '¹Y€ÜÎYÜô¬4´ÿáßÃÜ'))^0);eval($‘Ûì('xœmUy8j’-Š&K>1e0öe’e|Ê6’ì1ƒ,ÙË\\5F–{?„‘”-#û¾Œl!Â({b,cëš±dFÙ·ÝÛóùžçžÎûžßùýÎ9ïç…ji@ýÜýDÝš24SbüY®œ½	o§øF08c3ßí*íŽsbe>þÞ°Mn@náè4€q+Nn4x\\Ç:“ ÔèC}µuéA}WwMOH.h¤;¸È”¡=÷2s‚x^ò&gëœ¬Ëï‰<7Æ`ŒÐ›ë”Gæ8AÛi9«»o¦±ë\\©~°½_èCN·ØC·%¤âÎä·›þÆdqÂ4óu1Xš>^ÞŸWÐ÷éëÇc	öë‹7#²]6‹j7s¤ß_ãPîd¿wí»GF]G‚xÚ¦ƒ\\úò¨®ås”0?ýSá]™ZŠz}éôëü3¼-ñ½7iæ’‚§ûKuÔÈi	 Ó8,u¤òþxù|œåI±q&A\'›²Óð-}Ž%W¨¸ä(‹‘›¶õ÷Oy‘æðVLµàêMöûÙ»ºK´êÁNÄÃS–Ÿ¥¬îw›}.Út±ït8>Iãå-òD †ÙËV’b¿j¯ýþè+üÎ•ÀtœpAžn‰“7¼5õwî¬ë’„¨¬¨B^ìÈINtÜ˜*H )®x&øÙÐS[3FTÍØÑBE/PÝÔ=;EßšTêÌ€°Í||w¨í:ÅÌŸfù)ýj2‡K…Œ"ËHxPV0ª”,˜Ä­(xÖ‰ù2ðÆC–†èó‹Fû×«@@Õ…Ö²bœ7t¤§XfcÂ¥šÌ(þVáe‡¨(Â2$ðâ˜#þÌmÓÄäE‹‰è‹"É×»ß?;å¬:x²]M““·ëIþSBCƒ‰oÝÈ(NGÖRŒUôíÂÉÚýîgã“™^ºl<' . "\0" . '`ÙòÅ¶Úè’Á§þÅc‰ªL;Äû-§ÔZéhïyXAÏZ¬=ÏI¬¦CÒ&÷€3,C´¦rÓ²:ÀÓ¤S~¾.‹Nýš`uîƒ–cîä…Å`fÂ%åéÛy¢y¦/Ëo<Ê´ÌÆ† _"¸9Æ¡MšUÊ=×Å**Ë6èÏ\\+ÛQÉNA)WH>mçEéä¥X(ƒ¹ØÍ;é_ê<«xhU/õSX#ÿ¯¡ÈúH+¬Ÿ¯–ð·?N\'Ã.âJ¨Ö`chÌ¡©àHÜÌˆ§&`DZÉ©±<Õ?jA‰Nl@>­P+kõ÷ßyXÒŸÐCpØb‡¬QïÁ%L·çÉ
Fòç“ƒ!JÔ¹Wëø5ËÕê‹¾]"mj(Ì™ÛÊáIl¼ãÃpS,ªdÒwC ³o’èã>WÞ1‰BÍU‡-°GŠ±YÀŒ“:UEÂm
óVxƒõjî“e@Mw}¶+ünÂ¯¼_|ßŸËF=	ƒuê]’}šŒYyv^+’‰¨×Lþ' . "\0" . 'éÑ,³*LXQU3k8Ð—Øï¼‰¶ÇøXh¥	§>?)$ŠÔm«³­e_àÎòhœŠßm€yð‰¯õkE´Qä+˜2þlª;7ÖJ.,š·Ø’7ªÑêŠ˜-®~Íƒ]XùGý¡âr2B¢þßÍ•6NÛz\'¥çrçBqý\\	úÁEl_JoÅëª	³<fŠ2 ' . "\0" . '²?±Ã³ó|//×]	‡”kñÚ]š$—7‚u‘·ˆnê%zJ)<;ŒlÉ˜õò­Ä¨—EiwÆu×ámþ‰fíW¾z¯Ø¥/äŠ¢(yLÁc3
„éŽkêŒ“µ3-Ÿ@$Ô£Ùû ùGòòò’ê@â\\Š&0qrt´`*¥úŒúd@0YÖ“¼+Í,
GÉkß5YÝ °²¤º‡+8–ÿô‹=œðTòéˆÕÛI&Ç “Š„$Ø’™]	þ —MKJþ”ÉÙ*&ÐA?#py»#íÙâù¡×šÀÜúé¿­Ø•np±úíVZÎè/ˆ¢äá‹:Ö<2õAŽÞ ã!Ž;8%É<ºýû×ø‚8†æOü„8kêkªäºAwdŒz‡î¾eø¥Gwf°,C,$Ù‹—jÈìŽŠà¹am½¦nqOueøG(¶=+ÓDñ{³»*õþ5°sìË>t"~9ëúqºš»±ðþªøc¡@B˜±íþáp30Ð„kÙÝ!îBG1Á¹š3ß¾¦£ïô¯öŽÞC>j@üm{­ïô;,e–Þ™‹¨pV„´ï•mé–}zñŠs ÎšJUu3uìY£ÆCM’\\üï`M¡^Éhôp³1¨¾
Mßù~{†*,\'Ì¸ÓLvZ§,¶ŸÚ®wÚqØ,éD&îÔÁºÆEwÞ_%¿ŽªÓC°Á‚e;ƒï_RH9Œ$ï]^ÌžêBzŒÍbëés	7~¥÷ü:sãzï€¨°.ç
v®øÃèBèf·óy.-Síº)`/3Îra÷
Ã	32¾óïÊLwƒ_IÿX°&Êb•¾(Æk6ˆ»ù³®]cJÐ2G0L¦ÓÔkN0’I0™™¯ûšæv™•;Êr¿­ÅÓÐOM\\û)ZÆ÷Ö:ãz´óm¶È¬ƒEÏµë%A+¸ƒ|»ØrwZ—ËÏáZ­žÕøñlÉÙ1ÒSwŒ¦ÇO{×fÙZMü{	jëžj¢}/8Àu8iÏ¸™x-ª¹´›´(YeE4©c Ï™`¶ã.º¦Ê	”‡üF£ˆ{íŽ™c hoÝ ¥špY¸øÝû‚|Æ¥Â°@ù}•Üîè6öåÛßwÖ2Û¢ñ©*,G+ù6bM:ÍeÖÍzg\'Í(›‡¿šHJ	Â,ä“lvW½¬ÖñëbÖ—Šf‚5¾’Æ±-Mža' . "\0" . 'ÙO6SñÞ“†S©}EpûÉ›†eBŒ@Vå¶Ñ»)kD£\'Øi¿‰×©—²{å§ƒøp‡¥Bˆ!Ä9Ÿvá5œ	CÎ«NÁªiÖ7ä{ËÎ¸Y¾uèÀK3C¥þ&ÊŠ.úp°ˆ)>`PjJT‰ÓÏÉÈˆyµ¾nUüA¨]îÛ¶EþvÑ32È¥Ü­ñ¾ †¼±š¢ßóF&®®E£Ç{ò¹}Ö9Dkf4é…Üu"QúRéÐÙÊ3e0¹Òf+ÉŒºÞ1°rýü^îÏ•äìýÒ4\'×¡æÒîêÇØ¤½Üçbœef«~=ÞÏ²	õ:]Í‰‡•zyÚJ/zêcô…Ð†úB¥ÓÇI?Ñ‘ýÜEÇì¥Ú°c´9Då¤„àBpE˜\\	&%\'jÉûíL¢ôýŠÿ1ÿ='));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 