<?php
/* CONFIG BY FChyd
SUBSCRIBE YT CHANNEL E. SCRIPTER
ILEGAL TO DECRYPT THIS SCRIPT
ILEGAL TO USE MULTIPLE SESSION*/



//  SECURE TOKEN
$keyy = "AIzaSyCL0VbkYb31UB-SgGT14DnF1E0EbqpVd10";
$refresh = "AG8BCncIrTruLvZ5CQwc6oDzRoqTT5zoJtAni52vheIyXTsBCItd2vaePUlHOapITziTxI6E2udL-S1YjJUnVLT9Rz0o_wECwuAi5CpvEISLZCs8Dk39D1NWeb7ZsC3B9eCtJr5OnJH7--LJLYn8JgdMLMlcODljhiZeC1JtZ8tKACBO78er_npt2WPzheW9f9TszJLg7S_IeFzfBwBWjPaMLb16hoPCYtVUrgqjrveZ89dCrRHIEnuTaV6YzUBHPHvZNL-mpg2uODNdE_pOkqf1Prr8GlVbdMvEZmHG94RBtAyDoRST5NghSxx8B6HROTdz8m_g2DgkT9yHUCrAnATwQSw1BS1Fc_1JJPfMMRCCpfojKlGFYdSp617YWISCbOlfSb_JHib1LwqAdZx_zEaRXoIKKQIkZZV4a8u5fkJ0kWwh_aabkM0";


// DATA USER
$user = "ChlxvgHNzubrIangIMZ2KVlNPwp1";



