<?php

// ISI SEMUA DATA DI BAWAH INI
// PERHATIKAN BAGAIMANA ADMIN MENGISI DATANYA
// JANGAN LUPA SUPPORT CHANNEL ADMIN

$user = "xxxx";
$cookie = "xxxx";

// ISI ANGKA 1 JIKA MAU MENGKALAIM
// ISI ANGKA 0 JIKA TIDAK

$DOGE = "1";
