<?
//PERHATIKAN CARA ADMIN MENGISI
//GANTI BAGIAN XXX SAJA
//JANGAN HILANGKAN TANDA KUTIP(") DAN TITIK KOMA(;) DI BAGIAN SCRIPT
//JIKA SALAH MENGISI, BOT TIDAK AKAN BERJALAN DENGAN NORMAL

$url = "xxx";
$user = "xxx";
$cookie = "xxx";